from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DelayCmdWidget(object):
    def setupUi(self, DelayCmdWidget):
        DelayCmdWidget.setObjectName("DelayCmdWidget")
        DelayCmdWidget.resize(400, 30)
        DelayCmdWidget.setMinimumSize(QtCore.QSize(400, 30))
        DelayCmdWidget.setMaximumSize(QtCore.QSize(400, 30))
        self.layoutWidget = QtWidgets.QWidget(DelayCmdWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 4, 181, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.waitForLabel = QtWidgets.QLabel(self.layoutWidget)
        self.waitForLabel.setMinimumSize(QtCore.QSize(50, 20))
        self.waitForLabel.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.waitForLabel.setFont(font)
        self.waitForLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.waitForLabel.setObjectName("waitForLabel")
        self.horizontalLayout.addWidget(self.waitForLabel)
        self.delayAmount = QtWidgets.QSpinBox(self.layoutWidget)
        self.delayAmount.setMinimumSize(QtCore.QSize(40, 20))
        self.delayAmount.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.delayAmount.setFont(font)
        self.delayAmount.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.delayAmount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.delayAmount.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.delayAmount.setMinimum(1)
        self.delayAmount.setMaximum(10000)
        self.delayAmount.setProperty("value", 1)
        self.delayAmount.setObjectName("delayAmount")
        self.horizontalLayout.addWidget(self.delayAmount)
        self.delayTimeType = QtWidgets.QComboBox(self.layoutWidget)
        self.delayTimeType.setMinimumSize(QtCore.QSize(40, 20))
        self.delayTimeType.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.delayTimeType.setFont(font)
        self.delayTimeType.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.delayTimeType.setEditable(False)
        self.delayTimeType.setObjectName("delayTimeType")
        self.delayTimeType.addItem("")
        self.delayTimeType.addItem("")
        self.horizontalLayout.addWidget(self.delayTimeType)

        self.retranslateUi(DelayCmdWidget)
        QtCore.QMetaObject.connectSlotsByName(DelayCmdWidget)

    def retranslateUi(self, DelayCmdWidget):
        _translate = QtCore.QCoreApplication.translate
        DelayCmdWidget.setWindowTitle(_translate("DelayCmdWidget", "DelayCmdWidget"))
        self.waitForLabel.setText(_translate("DelayCmdWidget", "Wait for"))
        self.delayTimeType.setItemText(0, _translate("DelayCmdWidget", "s"))
        self.delayTimeType.setItemText(1, _translate("DelayCmdWidget", "ms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DelayCmdWidget = QtWidgets.QWidget()
    ui = Ui_DelayCmdWidget()
    ui.setupUi(DelayCmdWidget)
    DelayCmdWidget.show()
    sys.exit(app.exec_())
